# Generated by Django 4.2 on 2023-04-24 17:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("events", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="event", name="workload", field=models.IntegerField(),
        ),
    ]
