# Generated by Django 4.2 on 2023-04-25 12:30

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("events", "0002_alter_event_workload"),
    ]

    operations = [
        migrations.AddField(
            model_name="event",
            name="participant",
            field=models.ManyToManyField(
                null=True, related_name="event_participant", to=settings.AUTH_USER_MODEL
            ),
        ),
    ]
